// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FileController from "./file_controller"
application.register("file", FileController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import InputController from "./input_controller"
application.register("input", InputController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)
