inherit_mode:
  merge:
    - Exclude

require:
  - standard

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-capybara
  - standard-custom
  - standard-performance
  - standard-rails

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
  standard-rails: config/base.yml

AllCops:
  NewCops: enable

Layout/ExtraSpacing:
  Exclude:
    - config/**/*.rb
    - db/**/*.rb

Lint/RedundantDirGlobSort:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true



Performance/TimesMap:
  Enabled: true

Performance/Sum:
  Enabled: true



RSpec/ExampleLength:
  Enabled: false

RSpec/ContextWording:
  AllowedPatterns:
    - ^by default$
  Prefixes:
    - "on"
    - when
    - with
    - without

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
