x-app: &app
  build:
    context: .
    target: development
  environment: &env
    DB_USER: scrooge
    DB_PASS: 123456
    DB_HOST: postgres
    REDIS_URL: redis://redis:6379
  volumes:
    - .:/scrooge
    - bundle:/usr/local/bundle
  depends_on:
    - postgres
    - redis

services:
  web:
    <<: *app
    environment:
      <<: *env
      DEMO_USER_EMAIL: scrooge@example.com
      DEMO_USER_PASS: 123456
      CHROME_HOST: 172.17.0.1
      CHROME_PORT: 9515
    ports:
      - "3000:3000"
      - "3030:3030"
    depends_on:
      - sidekiq
  sidekiq:
    <<: *app
    command: bundle exec sidekiq
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: scrooge
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.5-alpine

volumes:
  postgres_data:
  bundle:
