default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  database: <%= ENV["DB_NAME"].presence || "#{ENV["DB_USER"]}_#{ENV.fetch("RAILS_ENV", "development")}" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
