AddModelVirtualAttributeCheck: {}
AlwaysAddDbIndexCheck: {}
# CheckSaveReturnValueCheck: {}
# CheckDestroyReturnValueCheck: {}
DefaultScopeIsEvilCheck: {}
DryBundlerInCapistranoCheck: {}
# HashSyntaxCheck: {}
IsolateSeedDataCheck: {}
KeepFindersOnTheirOwnModelCheck: {}
LawOfDemeterCheck: {}
# LongLineCheck:
#  max_line_length: 80
MoveCodeIntoControllerCheck: {}
MoveCodeIntoHelperCheck:
  array_count: 3
MoveCodeIntoModelCheck:
  use_count: 2
MoveFinderToNamedScopeCheck: {}
MoveModelLogicIntoModelCheck:
  use_count: 4
NeedlessDeepNestingCheck:
  nested_count: 2
NotRescueExceptionCheck: {}
NotUseDefaultRouteCheck: {}
NotUseTimeAgoInWordsCheck: {}
OveruseRouteCustomizationsCheck:
  customize_count: 3
ProtectMassAssignmentCheck: {}
RemoveEmptyHelpersCheck: {}
# RemoveTabCheck: {}
RemoveTrailingWhitespaceCheck: {}
RemoveUnusedMethodsInControllersCheck:
  except_methods:
    - ApplicationController#after_sign_out_path_for
    - Users::RegistrationsController#after_inactive_sign_up_path_for
    - Users::RegistrationsController#after_update_path_for
RemoveUnusedMethodsInHelpersCheck:
  except_methods: []
RemoveUnusedMethodsInModelsCheck:
  except_methods: []
ReplaceComplexCreationWithFactoryMethodCheck:
  attribute_assignment_count: 2
ReplaceInstanceVariableWithLocalVariableCheck: {}
RestrictAutoGeneratedRoutesCheck: {}
SimplifyRenderInControllersCheck: {}
SimplifyRenderInViewsCheck:
  ignored_files:
    - app/views/categories/index.html.erb
# UseBeforeFilterCheck:
#  customize_count: 2
UseModelAssociationCheck: {}
UseMultipartAlternativeAsContentTypeOfEmailCheck: {}
# UseParenthesesInMethodDefCheck: {}
UseObserverCheck: {}
UseQueryAttributeCheck: {}
UseSayWithTimeInMigrationsCheck: {}
UseScopeAccessCheck: {}
UseTurboSprocketsRails3Check: {}
